// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Nj9gheEdUdl2ekhtTFwkXg6XKVW2rIw',
    appId: '1:846744294943:web:7d3f0b54648deef251672a',
    messagingSenderId: '846744294943',
    projectId: 'airplane-2addf',
    authDomain: 'airplane-2addf.firebaseapp.com',
    storageBucket: 'airplane-2addf.appspot.com',
    measurementId: 'G-8TE4JGYBT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-VdGq14W_ThI6W4HTDuykL6atc_RedQ',
    appId: '1:846744294943:android:6383d9fa3ff8354951672a',
    messagingSenderId: '846744294943',
    projectId: 'airplane-2addf',
    storageBucket: 'airplane-2addf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Jrn4TDKaij1RCZc2CxVgIJPwCenjPqM',
    appId: '1:846744294943:ios:ec8140c2dd19b20251672a',
    messagingSenderId: '846744294943',
    projectId: 'airplane-2addf',
    storageBucket: 'airplane-2addf.appspot.com',
    iosClientId: '846744294943-mtch6pf3pel1othmvjcgk54frc40if6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.airplane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Jrn4TDKaij1RCZc2CxVgIJPwCenjPqM',
    appId: '1:846744294943:ios:ec8140c2dd19b20251672a',
    messagingSenderId: '846744294943',
    projectId: 'airplane-2addf',
    storageBucket: 'airplane-2addf.appspot.com',
    iosClientId: '846744294943-mtch6pf3pel1othmvjcgk54frc40if6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.airplane',
  );
}
